# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Looper' do

    pod 'FBSDKLoginKit'
    pod 'AFNetworking', '~> 3.0'
    pod 'IQKeyboardManager'
    pod 'NYAlertViewController'             #, '~> 1.3'
    pod 'GoogleMaps'
    pod 'ActionSheetPicker-3.0', '~> 2.0.5'
    pod 'JSONModel'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'DateTools'
end

